name: Update Kernel

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - main
  schedule:
    # every 6 hours
    - cron: '0 */6 * * *'

jobs:
  update_kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get latest linux kernel version for 5.10
      id: get_latest_kernel
      run: |
        echo latestversion=$(curl -s https://www.kernel.org/releases.json | jq -r '.releases[] | select(.version | startswith("5.10")) | .version' | sort -V | tail -n 1) >> $GITHUB_OUTPUT
    - name: Update kernel version file
      run: |
        echo "${{ steps.get_latest_kernel.outputs.latestversion }}" > versions/kernel
    - name: Commit changes
      uses: EndBug/add-and-commit@f91c6724df48d647dd523d222e655d20432cf7d3
      id: commit
      with:
        default_author: github_actions
        message: 'Bump kernel version to ${{ steps.get_latest_kernel.outputs.latestversion }}'
        add: 'versions/kernel'
        push: true
        tag: 'v${{ steps.get_latest_kernel.outputs.latestversion }}'
    - name: Dispatch release event
      if: steps.commit.outputs.committed == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: release
        client-payload: '{"ref": "v${{ steps.get_latest_kernel.outputs.latestversion }}"}'
