name: Update Firecracker version

permissions:
  contents: write

on:
  schedule:
    # every 6 hours
    - cron: '0 */6 * * *'

jobs:
  update_firecracker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

    - name: Get latest firecracker version
      id: get_latest_firecracker
      run: |
        echo latestversion=$(curl -s https://api.github.com/repos/firecracker-microvm/firecracker/releases/latest | jq -r '.tag_name') >> $GITHUB_OUTPUT

    - name: Update firecracker version file
      run: |
        echo "${{ steps.get_latest_firecracker.outputs.latestversion }}" > versions/firecracker

    - name: Commit changes
      uses: EndBug/add-and-commit@70e21b325f8ec72c3aeeedab71de5662d71a2fc1
      with:
        default_author: github_actions
        message: 'Bump firecracker version to ${{ steps.get_latest_firecracker.outputs.latestversion }}'
        add: 'versions/firecracker'
