name: Update Kernel

permissions:
  contents: write

on:
  push:
    branches:
      - main
  # schedule:
  #   # Every day at 2am
  #   - cron: '0 2 * * *'

jobs:
  update_kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get latest linux kernel version for 5.10
      id: get_latest_kernel
      run: |
        curl -s https://www.kernel.org/releases.json | jq -r '.releases[] | select(.version | startswith("5.10")) | .version' | sort -V | tail -n 1
    - name: Update kernel version file
      run: |
        echo "${{ steps.get_latest_kernel.outputs.stdout }}" > versions/kernel
    - name: Commit changes
      uses: EndBug/add-and-commit@f91c6724df48d647dd523d222e655d20432cf7d3
      with:
        default_author: github_actions
        message: 'Bump kernel version'
        add: 'versions/kernel'
        push: false
        tag: 'debug/${{ steps.get_latest_kernel.outputs.stdout }}'
